/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skel.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitDef(Def *t) {} //abstract class
void Skeleton::visitField(Field *t) {} //abstract class
void Skeleton::visitArg(Arg *t) {} //abstract class
void Skeleton::visitStm(Stm *t) {} //abstract class
void Skeleton::visitIdIn(IdIn *t) {} //abstract class
void Skeleton::visitExp(Exp *t) {} //abstract class
void Skeleton::visitType(Type *t) {} //abstract class

void Skeleton::visitPDefs(PDefs *p_defs)
{
  /* Code For PDefs Goes Here */

  if (p_defs->listdef_) p_defs->listdef_->accept(this);

}

void Skeleton::visitDFun(DFun *d_fun)
{
  /* Code For DFun Goes Here */

  if (d_fun->type_) d_fun->type_->accept(this);
  visitId(d_fun->id_);
  if (d_fun->listarg_) d_fun->listarg_->accept(this);
  if (d_fun->liststm_) d_fun->liststm_->accept(this);

}

void Skeleton::visitDStruct(DStruct *d_struct)
{
  /* Code For DStruct Goes Here */

  visitId(d_struct->id_);
  if (d_struct->listfield_) d_struct->listfield_->accept(this);

}

void Skeleton::visitDStructDer(DStructDer *d_struct_der)
{
  /* Code For DStructDer Goes Here */

  visitId(d_struct_der->id_);
  if (d_struct_der->type_) d_struct_der->type_->accept(this);
  if (d_struct_der->listfield_) d_struct_der->listfield_->accept(this);

}

void Skeleton::visitFDecl(FDecl *f_decl)
{
  /* Code For FDecl Goes Here */

  if (f_decl->type_) f_decl->type_->accept(this);
  visitId(f_decl->id_);

}

void Skeleton::visitADecl(ADecl *a_decl)
{
  /* Code For ADecl Goes Here */

  if (a_decl->type_) a_decl->type_->accept(this);
  visitId(a_decl->id_);

}

void Skeleton::visitSExp(SExp *s_exp)
{
  /* Code For SExp Goes Here */

  if (s_exp->exp_) s_exp->exp_->accept(this);

}

void Skeleton::visitSDecls(SDecls *s_decls)
{
  /* Code For SDecls Goes Here */

  if (s_decls->type_) s_decls->type_->accept(this);
  if (s_decls->listidin_) s_decls->listidin_->accept(this);

}

void Skeleton::visitSReturn(SReturn *s_return)
{
  /* Code For SReturn Goes Here */

  if (s_return->exp_) s_return->exp_->accept(this);

}

void Skeleton::visitSReturnV(SReturnV *s_return_v)
{
  /* Code For SReturnV Goes Here */


}

void Skeleton::visitSWhile(SWhile *s_while)
{
  /* Code For SWhile Goes Here */

  if (s_while->exp_) s_while->exp_->accept(this);
  if (s_while->stm_) s_while->stm_->accept(this);

}

void Skeleton::visitSDoWhile(SDoWhile *s_do_while)
{
  /* Code For SDoWhile Goes Here */

  if (s_do_while->stm_) s_do_while->stm_->accept(this);
  if (s_do_while->exp_) s_do_while->exp_->accept(this);

}

void Skeleton::visitSFor(SFor *s_for)
{
  /* Code For SFor Goes Here */

  if (s_for->exp_1) s_for->exp_1->accept(this);
  if (s_for->exp_2) s_for->exp_2->accept(this);
  if (s_for->exp_3) s_for->exp_3->accept(this);
  if (s_for->stm_) s_for->stm_->accept(this);

}

void Skeleton::visitSBlock(SBlock *s_block)
{
  /* Code For SBlock Goes Here */

  if (s_block->liststm_) s_block->liststm_->accept(this);

}

void Skeleton::visitSIfElse(SIfElse *s_if_else)
{
  /* Code For SIfElse Goes Here */

  if (s_if_else->exp_) s_if_else->exp_->accept(this);
  if (s_if_else->stm_1) s_if_else->stm_1->accept(this);
  if (s_if_else->stm_2) s_if_else->stm_2->accept(this);

}

void Skeleton::visitSTry(STry *s_try)
{
  /* Code For STry Goes Here */

  if (s_try->stm_1) s_try->stm_1->accept(this);
  if (s_try->type_) s_try->type_->accept(this);
  visitId(s_try->id_);
  if (s_try->stm_2) s_try->stm_2->accept(this);

}

void Skeleton::visitIdNoInit(IdNoInit *id_no_init)
{
  /* Code For IdNoInit Goes Here */

  visitId(id_no_init->id_);

}

void Skeleton::visitIdInit(IdInit *id_init)
{
  /* Code For IdInit Goes Here */

  visitId(id_init->id_);
  if (id_init->exp_) id_init->exp_->accept(this);

}

void Skeleton::visitETrue(ETrue *e_true)
{
  /* Code For ETrue Goes Here */


}

void Skeleton::visitEFalse(EFalse *e_false)
{
  /* Code For EFalse Goes Here */


}

void Skeleton::visitEInt(EInt *e_int)
{
  /* Code For EInt Goes Here */

  visitInteger(e_int->integer_);

}

void Skeleton::visitEDouble(EDouble *e_double)
{
  /* Code For EDouble Goes Here */

  visitDouble(e_double->double_);

}

void Skeleton::visitEId(EId *e_id)
{
  /* Code For EId Goes Here */

  visitId(e_id->id_);

}

void Skeleton::visitEApp(EApp *e_app)
{
  /* Code For EApp Goes Here */

  visitId(e_app->id_);
  if (e_app->listexp_) e_app->listexp_->accept(this);

}

void Skeleton::visitEProj(EProj *e_proj)
{
  /* Code For EProj Goes Here */

  if (e_proj->exp_) e_proj->exp_->accept(this);
  visitId(e_proj->id_);

}

void Skeleton::visitEPIncr(EPIncr *ep_incr)
{
  /* Code For EPIncr Goes Here */

  if (ep_incr->exp_) ep_incr->exp_->accept(this);

}

void Skeleton::visitEPDecr(EPDecr *ep_decr)
{
  /* Code For EPDecr Goes Here */

  if (ep_decr->exp_) ep_decr->exp_->accept(this);

}

void Skeleton::visitEIncr(EIncr *e_incr)
{
  /* Code For EIncr Goes Here */

  if (e_incr->exp_) e_incr->exp_->accept(this);

}

void Skeleton::visitEDecr(EDecr *e_decr)
{
  /* Code For EDecr Goes Here */

  if (e_decr->exp_) e_decr->exp_->accept(this);

}

void Skeleton::visitEUPlus(EUPlus *eu_plus)
{
  /* Code For EUPlus Goes Here */

  if (eu_plus->exp_) eu_plus->exp_->accept(this);

}

void Skeleton::visitEUMinus(EUMinus *eu_minus)
{
  /* Code For EUMinus Goes Here */

  if (eu_minus->exp_) eu_minus->exp_->accept(this);

}

void Skeleton::visitETimes(ETimes *e_times)
{
  /* Code For ETimes Goes Here */

  if (e_times->exp_1) e_times->exp_1->accept(this);
  if (e_times->exp_2) e_times->exp_2->accept(this);

}

void Skeleton::visitEDiv(EDiv *e_div)
{
  /* Code For EDiv Goes Here */

  if (e_div->exp_1) e_div->exp_1->accept(this);
  if (e_div->exp_2) e_div->exp_2->accept(this);

}

void Skeleton::visitEPlus(EPlus *e_plus)
{
  /* Code For EPlus Goes Here */

  if (e_plus->exp_1) e_plus->exp_1->accept(this);
  if (e_plus->exp_2) e_plus->exp_2->accept(this);

}

void Skeleton::visitEMinus(EMinus *e_minus)
{
  /* Code For EMinus Goes Here */

  if (e_minus->exp_1) e_minus->exp_1->accept(this);
  if (e_minus->exp_2) e_minus->exp_2->accept(this);

}

void Skeleton::visitETwc(ETwc *e_twc)
{
  /* Code For ETwc Goes Here */

  if (e_twc->exp_1) e_twc->exp_1->accept(this);
  if (e_twc->exp_2) e_twc->exp_2->accept(this);

}

void Skeleton::visitELt(ELt *e_lt)
{
  /* Code For ELt Goes Here */

  if (e_lt->exp_1) e_lt->exp_1->accept(this);
  if (e_lt->exp_2) e_lt->exp_2->accept(this);

}

void Skeleton::visitEGt(EGt *e_gt)
{
  /* Code For EGt Goes Here */

  if (e_gt->exp_1) e_gt->exp_1->accept(this);
  if (e_gt->exp_2) e_gt->exp_2->accept(this);

}

void Skeleton::visitELtEq(ELtEq *e_lt_eq)
{
  /* Code For ELtEq Goes Here */

  if (e_lt_eq->exp_1) e_lt_eq->exp_1->accept(this);
  if (e_lt_eq->exp_2) e_lt_eq->exp_2->accept(this);

}

void Skeleton::visitEGtEq(EGtEq *e_gt_eq)
{
  /* Code For EGtEq Goes Here */

  if (e_gt_eq->exp_1) e_gt_eq->exp_1->accept(this);
  if (e_gt_eq->exp_2) e_gt_eq->exp_2->accept(this);

}

void Skeleton::visitEEq(EEq *e_eq)
{
  /* Code For EEq Goes Here */

  if (e_eq->exp_1) e_eq->exp_1->accept(this);
  if (e_eq->exp_2) e_eq->exp_2->accept(this);

}

void Skeleton::visitENEq(ENEq *en_eq)
{
  /* Code For ENEq Goes Here */

  if (en_eq->exp_1) en_eq->exp_1->accept(this);
  if (en_eq->exp_2) en_eq->exp_2->accept(this);

}

void Skeleton::visitEAnd(EAnd *e_and)
{
  /* Code For EAnd Goes Here */

  if (e_and->exp_1) e_and->exp_1->accept(this);
  if (e_and->exp_2) e_and->exp_2->accept(this);

}

void Skeleton::visitEOr(EOr *e_or)
{
  /* Code For EOr Goes Here */

  if (e_or->exp_1) e_or->exp_1->accept(this);
  if (e_or->exp_2) e_or->exp_2->accept(this);

}

void Skeleton::visitEAss(EAss *e_ass)
{
  /* Code For EAss Goes Here */

  if (e_ass->exp_1) e_ass->exp_1->accept(this);
  if (e_ass->exp_2) e_ass->exp_2->accept(this);

}

void Skeleton::visitECond(ECond *e_cond)
{
  /* Code For ECond Goes Here */

  if (e_cond->exp_1) e_cond->exp_1->accept(this);
  if (e_cond->exp_2) e_cond->exp_2->accept(this);
  if (e_cond->exp_3) e_cond->exp_3->accept(this);

}

void Skeleton::visitEThrow(EThrow *e_throw)
{
  /* Code For EThrow Goes Here */

  if (e_throw->exp_) e_throw->exp_->accept(this);

}

void Skeleton::visitType_bool(Type_bool *type_bool)
{
  /* Code For Type_bool Goes Here */


}

void Skeleton::visitType_int(Type_int *type_int)
{
  /* Code For Type_int Goes Here */


}

void Skeleton::visitType_double(Type_double *type_double)
{
  /* Code For Type_double Goes Here */


}

void Skeleton::visitType_void(Type_void *type_void)
{
  /* Code For Type_void Goes Here */


}

void Skeleton::visitType_exception(Type_exception *type_exception)
{
  /* Code For Type_exception Goes Here */


}

void Skeleton::visitTypeId(TypeId *type_id)
{
  /* Code For TypeId Goes Here */

  visitId(type_id->id_);

}


void Skeleton::visitListDef(ListDef *list_def)
{
  for (ListDef::iterator i = list_def->begin() ; i != list_def->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListField(ListField *list_field)
{
  for (ListField::iterator i = list_field->begin() ; i != list_field->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListArg(ListArg *list_arg)
{
  for (ListArg::iterator i = list_arg->begin() ; i != list_arg->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListStm(ListStm *list_stm)
{
  for (ListStm::iterator i = list_stm->begin() ; i != list_stm->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListIdIn(ListIdIn *list_id_in)
{
  for (ListIdIn::iterator i = list_id_in->begin() ; i != list_id_in->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListExp(ListExp *list_exp)
{
  for (ListExp::iterator i = list_exp->begin() ; i != list_exp->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListId(ListId *list_id)
{
  for (ListId::iterator i = list_id->begin() ; i != list_id->end() ; ++i)
  {
    visitId(*i) ;
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}

void Skeleton::visitId(Id x)
{
  /* Code for Id Goes Here */
}



